services:
  # PostgreSQL Database
  - type: pserv
    name: last-dance-db
    env: docker
    plan: free
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    envVars:
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_DB
        value: last_dance

  # Spring Boot Application
  - type: web
    name: be-last-dance
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/v1/actuator/health
    envVars:
      - key: POSTGRES_DB_SERVER_ADDRESS
        fromService:
          type: pserv
          name: last-dance-db
          property: host
      - key: POSTGRES_DB_SERVER_PORT
        fromService:
          type: pserv
          name: last-dance-db
          property: port
      - key: POSTGRES_USER
        fromService:
          type: pserv
          name: last-dance-db
          envVarKey: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        fromService:
          type: pserv
          name: last-dance-db
          envVarKey: POSTGRES_PASSWORD
      - key: JWT_SECRET_KEY
        generateValue: true