server:
  http2:
    enabled: true
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS}:${POSTGRES_DB_SERVER_PORT}/last_dance
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      pool-name: SpringBootBoilerplateHikariPool
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jta:
    enabled: false
  flyway:
    baseline-on-migrate: true
    schemas: public
    default-schema: public

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    "[org.springframework]": INFO
    "[com.hoxuanthai.be.lastdance]": INFO

jwt:
  secretKey: ${JWT_SECRET_KEY}
  issuer: www.hoxuanthai.id.vn
  expirationMinute: 20160 # 14 days

swagger:
  contact-name: Ho Xuan Thai
  contact-mail: thai.hx04@gmail.com
  contact-url: https://hoxuanthai.id.vn
  app-name: BE Last Dance
  app-description: "BE Last Dance. This project includes : Spring Boot(3.5.7), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 0.0.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
