server:
  http2:
    enabled: true
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/last_dance
    username: ${POSTGRES_USER:na}
    password: ${POSTGRES_PASSWORD:iTelecom@123}
    hikari:
      pool-name: SpringBootBoilerplateHikariPool
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jta:
    enabled: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.hoxuanthai.be.lastdance: INFO

jwt:
  secretKey: ${JWT_SECRET_KEY:secret}
  issuer: www.hoxuanthai.id.vn
  expirationMinute: 10

swagger:
  contact-name: Ho Xuan Thai
  contact-mail: thai.hx04@gmail.com
  contact-url: https://hoxuanthai.id.vn
  app-name: BE Last Dance
  app-description: "BE Last Dance. This project includes : Spring Boot(3.5.7), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API)"
  app-version: 0.0.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
